const express = require("express")
const db = require("./config/db")
require("colors")
require('dotenv').config({path : "./config/.env"})
const salesRoutes = require("./routes/salesRoutes")
const cors = require("cors")
db()
const app = express()
app.use(cors())
app.use(express.json())
app.use("/api", salesRoutes)
app.listen(process.env.PORT || 5000 , e=> console.log(`SERVER RUNNING http://localhost:${process.env.PORT || 5000}`.bgBlue.black))